spring:
  application:
    name: spring-cgv-24th

springdoc:
  paths-to-match: /api/**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

cgv:
  jwt:
    secret-base64: ${CGV_JWT_SECRET_BASE64}
    access-token-seconds: ${CGV_ACCESS_TOKEN_SECONDS:1800}
